# Site settings
title: ECON爱好者
header-img: img/home-bg2.jpg
email: #hanjo.odendaal@eighty20.co.za
description: "Another Note"
baseurl: "/econ_en"
url:  "http://snowdj.github.io/econ_en"
twitter_username: #safactaday
github_username:  #Eighty20
facebook_username:  #Eighty20-291937880846403
future: TRUE
gems:
  - jekyll-feed
  
  
# SNS settings
#RSS: false
weibo_username:     snowdj
#zhihu_username:     terrytangyuan
github_username:    snowdj
twitter_username:  snowdj1984
#facebook_username:  terrytangyuan
#linkedin_visitor_id: yuan-terry-tang-117ba962  
  
  
comments :
  provider : disqus
  disqus :
    short_name : snowdj
analytics :
  provider : #google
  google :
      tracking_id : # 'UA-70616211-1'
      
# Duoshuo settings
duoshuo_username: snowdj
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

      
      

# Build settings
markdown: kramdown
#markdown: redcarpet
highlighter: rouge
permalink: pretty
paginate: 5
# https://jekyllrb.com/docs/configuration/
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "_rmd", "slides", "other"]

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: "snowdj"

enable_mathjax: True
# Fill in your Google Analytics ID to track your website using GA
google_analytics: ""
